name: TestMergeToMain
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "This is step 1. It should run unconditionally."
          echo "merge = ${{ github.event.pull_request.merged }}"
          echo "event name= ${{ github.event_name }}"
          echo "action = ${{ github.event.action }}"
          echo "pr base ref = ${{ github.event.pull_request.base.ref }}"
      - name: On Merge Only
        if: ${{ github.event.pull_request.merged == true && contains(['main', 'shmain'], github.event.pull_request.base.ref) }}
        run: |
          echo "This step should only run when we merge a PR to main"
      