name: TestMergeToMain
on: 
  push:
    branches:
      - main
      - shmain
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "This is step 1. It should run unconditionally!"
          echo "action=${{ github.event.name }}"
      - name: On Merge Only
        if: ${{ github.event.pull_request.merged == true && contains(fromJSON('["main", "shmain"]'), github.event.pull_request.base.ref) }}
        run: |
          echo "This step should only run when we merge a PR to main or shmain"
      