name: TestMergeToMain
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "This is step 1. It should run unconditionally."
      - name: On Merge Only
        run: |
          echo "This step should only run when we merge a PR to main"
      