name: TestMergeToMain
on: 
  push:
    branches:
      - main
      - shmain
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "This is step 1. It should run unconditionally!"
          echo "merge = ${{ github.event.pull_request.merged }}"
          echo "event name= ${{ github.event_name }}"
          echo "action = ${{ github.event.action }}"
          echo "pr base ref = ${{ github.event.pull_request.base.ref }}"

          echo "action=${{ github.event_name }}"
      - name: On Merge Only
        if: ${{ github.event_name == 'push' }}
        env: 
          EVENT_DETAILS: ${{ toJSON(github.event) }}
        run: |
          echo "This step should only run when we merge a PR to main or shmain"
          echo "push base_ref=${{ github.event.push.base_ref }}"
          echo "push ref=${{ github.event.push.ref }}"
          echo "push repository=${{ github.event.push.repository.name }}"
          echo "EVENT_DETAILS=${EVENT_DETAILS}"
      